spring:
  profiles:
    active: test
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
#  http:
#      multipart:
#        max-request-size: 128KB
#        max-file-size: 128KB




